// Generated by rstantools.  Do not edit by hand.

/*
    bcgp is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bcgp is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bcgp.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_stanNonCompS_with_pred_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_stanNonCompS_with_pred");
    reader.add_event(2, 2, "include", "/functions/common_functions.stan");
    reader.add_event(2, 0, "start", "/functions/common_functions.stan");
    reader.add_event(369, 367, "end", "/functions/common_functions.stan");
    reader.add_event(369, 3, "restart", "model_stanNonCompS_with_pred");
    reader.add_event(427, 59, "end", "model_stanNonCompS_with_pred");
    return reader;
}
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, Eigen::Dynamic>
get_cor_mat(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& rho, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 20;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,rows(x));
        current_statement_begin__ = 21;
        int d(0);
        (void) d;  // dummy to suppress unused var warning
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,cols(x));
        current_statement_begin__ = 22;
        local_scalar_t__ tmp(DUMMY_VAR__);
        (void) tmp;  // dummy to suppress unused var warning
        stan::math::initialize(tmp, DUMMY_VAR__);
        stan::math::fill(tmp, DUMMY_VAR__);
        current_statement_begin__ = 23;
        validate_non_negative_index("dist4", "d", d);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> dist4(d);
        stan::math::initialize(dist4, DUMMY_VAR__);
        stan::math::fill(dist4, DUMMY_VAR__);
        current_statement_begin__ = 24;
        validate_non_negative_index("R", "n", n);
        validate_non_negative_index("R", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R(n, n);
        stan::math::initialize(R, DUMMY_VAR__);
        stan::math::fill(R, DUMMY_VAR__);
        current_statement_begin__ = 26;
        for (int i = 1; i <= (n - 1); ++i) {
            current_statement_begin__ = 27;
            stan::model::assign(R, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        1.0, 
                        "assigning variable R");
            current_statement_begin__ = 28;
            for (int j = (i + 1); j <= n; ++j) {
                current_statement_begin__ = 29;
                stan::math::assign(dist4, multiply(4.0, transpose(subtract(get_base1(x, i, "x", 1), get_base1(x, j, "x", 1)))));
                current_statement_begin__ = 30;
                stan::math::assign(tmp, 1.0);
                current_statement_begin__ = 31;
                for (int k = 1; k <= d; ++k) {
                    current_statement_begin__ = 32;
                    stan::math::assign(tmp, (tmp * pow(get_base1(rho, k, "rho", 1), pow(get_base1(dist4, k, "dist4", 1), 2))));
                }
                current_statement_begin__ = 34;
                stan::model::assign(R, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                            tmp, 
                            "assigning variable R");
                current_statement_begin__ = 35;
                stan::model::assign(R, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            tmp, 
                            "assigning variable R");
            }
        }
        current_statement_begin__ = 38;
        stan::model::assign(R, 
                    stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                    1, 
                    "assigning variable R");
        current_statement_begin__ = 40;
        return stan::math::promote_scalar<fun_return_scalar_t__>(R);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct get_cor_mat_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& rho, std::ostream* pstream__) const {
        return get_cor_mat(x, rho, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
get_cov_mat_ns(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& V,
                   const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& R,
                   const T2__& sigma2eps, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 63;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(R));
        current_statement_begin__ = 64;
        validate_non_negative_index("rootV", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> rootV(N);
        stan::math::initialize(rootV, DUMMY_VAR__);
        stan::math::fill(rootV, DUMMY_VAR__);
        stan::math::assign(rootV,stan::math::sqrt(V));
        current_statement_begin__ = 65;
        validate_non_negative_index("C", "N", N);
        validate_non_negative_index("C", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C(N, N);
        stan::math::initialize(C, DUMMY_VAR__);
        stan::math::fill(C, DUMMY_VAR__);
        stan::math::assign(C,add(quad_form_diag(R, rootV), diag_matrix(rep_vector(sigma2eps, N))));
        current_statement_begin__ = 68;
        return stan::math::promote_scalar<fun_return_scalar_t__>(C);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct get_cov_mat_ns_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& V,
                   const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& R,
                   const T2__& sigma2eps, std::ostream* pstream__) const {
        return get_cov_mat_ns(V, R, sigma2eps, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
get_cov_mat_s(const T0__& sigma2,
                  const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& R,
                  const T2__& sigma2eps, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 90;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(R));
        current_statement_begin__ = 91;
        validate_non_negative_index("C", "N", N);
        validate_non_negative_index("C", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C(N, N);
        stan::math::initialize(C, DUMMY_VAR__);
        stan::math::fill(C, DUMMY_VAR__);
        stan::math::assign(C,add(multiply(sigma2, R), diag_matrix(rep_vector(sigma2eps, N))));
        current_statement_begin__ = 93;
        return stan::math::promote_scalar<fun_return_scalar_t__>(C);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct get_cov_mat_s_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const T0__& sigma2,
                  const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& R,
                  const T2__& sigma2eps, std::ostream* pstream__) const {
        return get_cov_mat_s(sigma2, R, sigma2eps, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
combine_cor_mats(const T0__& w,
                     const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& G,
                     const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& L, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 115;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(G));
        current_statement_begin__ = 116;
        validate_non_negative_index("R", "N", N);
        validate_non_negative_index("R", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R(N, N);
        stan::math::initialize(R, DUMMY_VAR__);
        stan::math::fill(R, DUMMY_VAR__);
        stan::math::assign(R,add(multiply(w, G), multiply((1 - w), L)));
        current_statement_begin__ = 117;
        return stan::math::promote_scalar<fun_return_scalar_t__>(R);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct combine_cor_mats_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const T0__& w,
                     const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& G,
                     const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& L, std::ostream* pstream__) const {
        return combine_cor_mats(w, G, L, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, class RNG>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__>::type>::type, Eigen::Dynamic, 1>
gp_pred_noncomp_s_rng(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                          const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                          const T3__& beta0,
                          const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& rho,
                          const T5__& sigma2eps,
                          const T6__& sigma2, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 145;
        int n_pred(0);
        (void) n_pred;  // dummy to suppress unused var warning
        stan::math::fill(n_pred, std::numeric_limits<int>::min());
        stan::math::assign(n_pred,rows(x_pred));
        current_statement_begin__ = 146;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,rows(x));
        current_statement_begin__ = 147;
        int d(0);
        (void) d;  // dummy to suppress unused var warning
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,cols(x));
        current_statement_begin__ = 149;
        validate_non_negative_index("y_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred(n_pred);
        stan::math::initialize(y_pred, DUMMY_VAR__);
        stan::math::fill(y_pred, DUMMY_VAR__);
        {
        current_statement_begin__ = 152;
        validate_non_negative_index("y_pred_mean", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred_mean(n_pred);
        stan::math::initialize(y_pred_mean, DUMMY_VAR__);
        stan::math::fill(y_pred_mean, DUMMY_VAR__);
        current_statement_begin__ = 153;
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> y_pred_var_chol(n_pred, n_pred);
        stan::math::initialize(y_pred_var_chol, DUMMY_VAR__);
        stan::math::fill(y_pred_var_chol, DUMMY_VAR__);
        current_statement_begin__ = 155;
        int n_all(0);
        (void) n_all;  // dummy to suppress unused var warning
        stan::math::fill(n_all, std::numeric_limits<int>::min());
        stan::math::assign(n_all,(n_pred + n));
        current_statement_begin__ = 156;
        validate_non_negative_index("x_all", "n_all", n_all);
        validate_non_negative_index("x_all", "d", d);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> x_all(n_all, d);
        stan::math::initialize(x_all, DUMMY_VAR__);
        stan::math::fill(x_all, DUMMY_VAR__);
        stan::math::assign(x_all,append_row(x_pred, x));
        current_statement_begin__ = 157;
        validate_non_negative_index("R_all", "n_all", n_all);
        validate_non_negative_index("R_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R_all(n_all, n_all);
        stan::math::initialize(R_all, DUMMY_VAR__);
        stan::math::fill(R_all, DUMMY_VAR__);
        stan::math::assign(R_all,get_cor_mat(x_all, rho, pstream__));
        current_statement_begin__ = 158;
        validate_non_negative_index("C_all", "n_all", n_all);
        validate_non_negative_index("C_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_all(n_all, n_all);
        stan::math::initialize(C_all, DUMMY_VAR__);
        stan::math::fill(C_all, DUMMY_VAR__);
        stan::math::assign(C_all,get_cov_mat_s(sigma2, R_all, sigma2eps, pstream__));
        current_statement_begin__ = 159;
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_pred(n_pred, n_pred);
        stan::math::initialize(C_pred, DUMMY_VAR__);
        stan::math::fill(C_pred, DUMMY_VAR__);
        stan::math::assign(C_pred,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 160;
        validate_non_negative_index("C_L", "n", n);
        validate_non_negative_index("C_L", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L(n, n);
        stan::math::initialize(C_L, DUMMY_VAR__);
        stan::math::fill(C_L, DUMMY_VAR__);
        stan::math::assign(C_L,cholesky_decompose(stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::nil_index_list())), "C_all")));
        current_statement_begin__ = 161;
        validate_non_negative_index("C_cross", "n", n);
        validate_non_negative_index("C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_cross(n, n_pred);
        stan::math::initialize(C_cross, DUMMY_VAR__);
        stan::math::fill(C_cross, DUMMY_VAR__);
        stan::math::assign(C_cross,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 163;
        validate_non_negative_index("y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_minus_beta0(n);
        stan::math::initialize(y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(y_minus_beta0,subtract(y, beta0));
        current_statement_begin__ = 164;
        validate_non_negative_index("C_L_inv_y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> C_L_inv_y_minus_beta0(n);
        stan::math::initialize(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(C_L_inv_y_minus_beta0,mdivide_left_tri_low(C_L, y_minus_beta0));
        current_statement_begin__ = 165;
        validate_non_negative_index("C_L_inv_C_cross", "n", n);
        validate_non_negative_index("C_L_inv_C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L_inv_C_cross(n, n_pred);
        stan::math::initialize(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::fill(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::assign(C_L_inv_C_cross,mdivide_left_tri_low(C_L, C_cross));
        current_statement_begin__ = 167;
        stan::math::assign(y_pred_mean, add(beta0, multiply(transpose(C_L_inv_C_cross), C_L_inv_y_minus_beta0)));
        current_statement_begin__ = 168;
        stan::math::assign(y_pred_var_chol, cholesky_decompose(subtract(C_pred, multiply(transpose(C_L_inv_C_cross), C_L_inv_C_cross))));
        current_statement_begin__ = 171;
        stan::math::assign(y_pred, multi_normal_cholesky_rng(y_pred_mean, y_pred_var_chol, base_rng__));
        }
        current_statement_begin__ = 173;
        return stan::math::promote_scalar<fun_return_scalar_t__>(y_pred);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gp_pred_noncomp_s_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, class RNG>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__>::type>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                          const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                          const T3__& beta0,
                          const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& rho,
                          const T5__& sigma2eps,
                          const T6__& sigma2, RNG& base_rng__, std::ostream* pstream__) const {
        return gp_pred_noncomp_s_rng(x, y, x_pred, beta0, rho, sigma2eps, sigma2, base_rng__, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, class RNG>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__>::type>::type>::type, Eigen::Dynamic, 1>
gp_pred_comp_ns_rng(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                        const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                        const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                        const T3__& beta0,
                        const T4__& w,
                        const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& rhoL,
                        const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& rhoG,
                        const T7__& sigma2eps,
                        const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& V,
                        const Eigen::Matrix<T9__, Eigen::Dynamic, 1>& V_pred, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__>::type>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 206;
        int n_pred(0);
        (void) n_pred;  // dummy to suppress unused var warning
        stan::math::fill(n_pred, std::numeric_limits<int>::min());
        stan::math::assign(n_pred,rows(x_pred));
        current_statement_begin__ = 207;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,rows(x));
        current_statement_begin__ = 208;
        int d(0);
        (void) d;  // dummy to suppress unused var warning
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,cols(x));
        current_statement_begin__ = 210;
        validate_non_negative_index("y_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred(n_pred);
        stan::math::initialize(y_pred, DUMMY_VAR__);
        stan::math::fill(y_pred, DUMMY_VAR__);
        {
        current_statement_begin__ = 213;
        validate_non_negative_index("y_pred_mean", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred_mean(n_pred);
        stan::math::initialize(y_pred_mean, DUMMY_VAR__);
        stan::math::fill(y_pred_mean, DUMMY_VAR__);
        current_statement_begin__ = 214;
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> y_pred_var_chol(n_pred, n_pred);
        stan::math::initialize(y_pred_var_chol, DUMMY_VAR__);
        stan::math::fill(y_pred_var_chol, DUMMY_VAR__);
        current_statement_begin__ = 216;
        int n_all(0);
        (void) n_all;  // dummy to suppress unused var warning
        stan::math::fill(n_all, std::numeric_limits<int>::min());
        stan::math::assign(n_all,(n_pred + n));
        current_statement_begin__ = 217;
        validate_non_negative_index("x_all", "n_all", n_all);
        validate_non_negative_index("x_all", "d", d);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> x_all(n_all, d);
        stan::math::initialize(x_all, DUMMY_VAR__);
        stan::math::fill(x_all, DUMMY_VAR__);
        stan::math::assign(x_all,append_row(x_pred, x));
        current_statement_begin__ = 219;
        validate_non_negative_index("G_all", "n_all", n_all);
        validate_non_negative_index("G_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> G_all(n_all, n_all);
        stan::math::initialize(G_all, DUMMY_VAR__);
        stan::math::fill(G_all, DUMMY_VAR__);
        stan::math::assign(G_all,get_cor_mat(x_all, rhoG, pstream__));
        current_statement_begin__ = 220;
        validate_non_negative_index("L_all", "n_all", n_all);
        validate_non_negative_index("L_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> L_all(n_all, n_all);
        stan::math::initialize(L_all, DUMMY_VAR__);
        stan::math::fill(L_all, DUMMY_VAR__);
        stan::math::assign(L_all,get_cor_mat(x_all, rhoL, pstream__));
        current_statement_begin__ = 221;
        validate_non_negative_index("R_all", "n_all", n_all);
        validate_non_negative_index("R_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R_all(n_all, n_all);
        stan::math::initialize(R_all, DUMMY_VAR__);
        stan::math::fill(R_all, DUMMY_VAR__);
        stan::math::assign(R_all,combine_cor_mats(w, G_all, L_all, pstream__));
        current_statement_begin__ = 222;
        validate_non_negative_index("V_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> V_all(n_all);
        stan::math::initialize(V_all, DUMMY_VAR__);
        stan::math::fill(V_all, DUMMY_VAR__);
        stan::math::assign(V_all,append_row(V_pred, V));
        current_statement_begin__ = 223;
        validate_non_negative_index("C_all", "n_all", n_all);
        validate_non_negative_index("C_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_all(n_all, n_all);
        stan::math::initialize(C_all, DUMMY_VAR__);
        stan::math::fill(C_all, DUMMY_VAR__);
        stan::math::assign(C_all,get_cov_mat_ns(V_all, R_all, sigma2eps, pstream__));
        current_statement_begin__ = 225;
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_pred(n_pred, n_pred);
        stan::math::initialize(C_pred, DUMMY_VAR__);
        stan::math::fill(C_pred, DUMMY_VAR__);
        stan::math::assign(C_pred,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 226;
        validate_non_negative_index("C_L", "n", n);
        validate_non_negative_index("C_L", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L(n, n);
        stan::math::initialize(C_L, DUMMY_VAR__);
        stan::math::fill(C_L, DUMMY_VAR__);
        stan::math::assign(C_L,cholesky_decompose(stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::nil_index_list())), "C_all")));
        current_statement_begin__ = 227;
        validate_non_negative_index("C_cross", "n", n);
        validate_non_negative_index("C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_cross(n, n_pred);
        stan::math::initialize(C_cross, DUMMY_VAR__);
        stan::math::fill(C_cross, DUMMY_VAR__);
        stan::math::assign(C_cross,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 229;
        validate_non_negative_index("y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_minus_beta0(n);
        stan::math::initialize(y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(y_minus_beta0,subtract(y, beta0));
        current_statement_begin__ = 230;
        validate_non_negative_index("C_L_inv_y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> C_L_inv_y_minus_beta0(n);
        stan::math::initialize(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(C_L_inv_y_minus_beta0,mdivide_left_tri_low(C_L, y_minus_beta0));
        current_statement_begin__ = 231;
        validate_non_negative_index("C_L_inv_C_cross", "n", n);
        validate_non_negative_index("C_L_inv_C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L_inv_C_cross(n, n_pred);
        stan::math::initialize(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::fill(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::assign(C_L_inv_C_cross,mdivide_left_tri_low(C_L, C_cross));
        current_statement_begin__ = 233;
        stan::math::assign(y_pred_mean, add(beta0, multiply(transpose(C_L_inv_C_cross), C_L_inv_y_minus_beta0)));
        current_statement_begin__ = 234;
        stan::math::assign(y_pred_var_chol, cholesky_decompose(subtract(C_pred, multiply(transpose(C_L_inv_C_cross), C_L_inv_C_cross))));
        current_statement_begin__ = 237;
        stan::math::assign(y_pred, multi_normal_cholesky_rng(y_pred_mean, y_pred_var_chol, base_rng__));
        }
        current_statement_begin__ = 240;
        return stan::math::promote_scalar<fun_return_scalar_t__>(y_pred);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gp_pred_comp_ns_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, class RNG>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__>::type>::type>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                        const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                        const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                        const T3__& beta0,
                        const T4__& w,
                        const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& rhoL,
                        const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& rhoG,
                        const T7__& sigma2eps,
                        const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& V,
                        const Eigen::Matrix<T9__, Eigen::Dynamic, 1>& V_pred, RNG& base_rng__, std::ostream* pstream__) const {
        return gp_pred_comp_ns_rng(x, y, x_pred, beta0, w, rhoL, rhoG, sigma2eps, V, V_pred, base_rng__, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, class RNG>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__>::type>::type, Eigen::Dynamic, 1>
gp_pred_noncomp_ns_rng(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                           const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                           const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                           const T3__& beta0,
                           const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& rho,
                           const T5__& sigma2eps,
                           const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& V,
                           const Eigen::Matrix<T7__, Eigen::Dynamic, 1>& V_pred, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 271;
        int n_pred(0);
        (void) n_pred;  // dummy to suppress unused var warning
        stan::math::fill(n_pred, std::numeric_limits<int>::min());
        stan::math::assign(n_pred,rows(x_pred));
        current_statement_begin__ = 272;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,rows(x));
        current_statement_begin__ = 273;
        int d(0);
        (void) d;  // dummy to suppress unused var warning
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,cols(x));
        current_statement_begin__ = 275;
        validate_non_negative_index("y_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred(n_pred);
        stan::math::initialize(y_pred, DUMMY_VAR__);
        stan::math::fill(y_pred, DUMMY_VAR__);
        {
        current_statement_begin__ = 278;
        validate_non_negative_index("y_pred_mean", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred_mean(n_pred);
        stan::math::initialize(y_pred_mean, DUMMY_VAR__);
        stan::math::fill(y_pred_mean, DUMMY_VAR__);
        current_statement_begin__ = 279;
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> y_pred_var_chol(n_pred, n_pred);
        stan::math::initialize(y_pred_var_chol, DUMMY_VAR__);
        stan::math::fill(y_pred_var_chol, DUMMY_VAR__);
        current_statement_begin__ = 281;
        int n_all(0);
        (void) n_all;  // dummy to suppress unused var warning
        stan::math::fill(n_all, std::numeric_limits<int>::min());
        stan::math::assign(n_all,(n_pred + n));
        current_statement_begin__ = 282;
        validate_non_negative_index("x_all", "n_all", n_all);
        validate_non_negative_index("x_all", "d", d);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> x_all(n_all, d);
        stan::math::initialize(x_all, DUMMY_VAR__);
        stan::math::fill(x_all, DUMMY_VAR__);
        stan::math::assign(x_all,append_row(x_pred, x));
        current_statement_begin__ = 284;
        validate_non_negative_index("R_all", "n_all", n_all);
        validate_non_negative_index("R_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R_all(n_all, n_all);
        stan::math::initialize(R_all, DUMMY_VAR__);
        stan::math::fill(R_all, DUMMY_VAR__);
        stan::math::assign(R_all,get_cor_mat(x_all, rho, pstream__));
        current_statement_begin__ = 285;
        validate_non_negative_index("V_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> V_all(n_all);
        stan::math::initialize(V_all, DUMMY_VAR__);
        stan::math::fill(V_all, DUMMY_VAR__);
        stan::math::assign(V_all,append_row(V_pred, V));
        current_statement_begin__ = 286;
        validate_non_negative_index("C_all", "n_all", n_all);
        validate_non_negative_index("C_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_all(n_all, n_all);
        stan::math::initialize(C_all, DUMMY_VAR__);
        stan::math::fill(C_all, DUMMY_VAR__);
        stan::math::assign(C_all,get_cov_mat_ns(V_all, R_all, sigma2eps, pstream__));
        current_statement_begin__ = 288;
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_pred(n_pred, n_pred);
        stan::math::initialize(C_pred, DUMMY_VAR__);
        stan::math::fill(C_pred, DUMMY_VAR__);
        stan::math::assign(C_pred,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 289;
        validate_non_negative_index("C_L", "n", n);
        validate_non_negative_index("C_L", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L(n, n);
        stan::math::initialize(C_L, DUMMY_VAR__);
        stan::math::fill(C_L, DUMMY_VAR__);
        stan::math::assign(C_L,cholesky_decompose(stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::nil_index_list())), "C_all")));
        current_statement_begin__ = 290;
        validate_non_negative_index("C_cross", "n", n);
        validate_non_negative_index("C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_cross(n, n_pred);
        stan::math::initialize(C_cross, DUMMY_VAR__);
        stan::math::fill(C_cross, DUMMY_VAR__);
        stan::math::assign(C_cross,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 292;
        validate_non_negative_index("y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_minus_beta0(n);
        stan::math::initialize(y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(y_minus_beta0,subtract(y, beta0));
        current_statement_begin__ = 293;
        validate_non_negative_index("C_L_inv_y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> C_L_inv_y_minus_beta0(n);
        stan::math::initialize(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(C_L_inv_y_minus_beta0,mdivide_left_tri_low(C_L, y_minus_beta0));
        current_statement_begin__ = 294;
        validate_non_negative_index("C_L_inv_C_cross", "n", n);
        validate_non_negative_index("C_L_inv_C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L_inv_C_cross(n, n_pred);
        stan::math::initialize(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::fill(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::assign(C_L_inv_C_cross,mdivide_left_tri_low(C_L, C_cross));
        current_statement_begin__ = 296;
        stan::math::assign(y_pred_mean, add(beta0, multiply(transpose(C_L_inv_C_cross), C_L_inv_y_minus_beta0)));
        current_statement_begin__ = 297;
        stan::math::assign(y_pred_var_chol, cholesky_decompose(subtract(C_pred, multiply(transpose(C_L_inv_C_cross), C_L_inv_C_cross))));
        current_statement_begin__ = 300;
        stan::math::assign(y_pred, multi_normal_cholesky_rng(y_pred_mean, y_pred_var_chol, base_rng__));
        }
        current_statement_begin__ = 303;
        return stan::math::promote_scalar<fun_return_scalar_t__>(y_pred);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gp_pred_noncomp_ns_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, class RNG>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__>::type>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                           const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                           const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                           const T3__& beta0,
                           const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& rho,
                           const T5__& sigma2eps,
                           const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& V,
                           const Eigen::Matrix<T7__, Eigen::Dynamic, 1>& V_pred, RNG& base_rng__, std::ostream* pstream__) const {
        return gp_pred_noncomp_ns_rng(x, y, x_pred, beta0, rho, sigma2eps, V, V_pred, base_rng__, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, class RNG>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__>::type>::type>::type, Eigen::Dynamic, 1>
gp_pred_comp_s_rng(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                       const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                       const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                       const T3__& beta0,
                       const T4__& w,
                       const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& rhoL,
                       const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& rhoG,
                       const T7__& sigma2eps,
                       const T8__& sigma2, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__>::type>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 338;
        int n_pred(0);
        (void) n_pred;  // dummy to suppress unused var warning
        stan::math::fill(n_pred, std::numeric_limits<int>::min());
        stan::math::assign(n_pred,rows(x_pred));
        current_statement_begin__ = 339;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,rows(x));
        current_statement_begin__ = 340;
        int d(0);
        (void) d;  // dummy to suppress unused var warning
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,cols(x));
        current_statement_begin__ = 342;
        validate_non_negative_index("y_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred(n_pred);
        stan::math::initialize(y_pred, DUMMY_VAR__);
        stan::math::fill(y_pred, DUMMY_VAR__);
        {
        current_statement_begin__ = 345;
        validate_non_negative_index("y_pred_mean", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred_mean(n_pred);
        stan::math::initialize(y_pred_mean, DUMMY_VAR__);
        stan::math::fill(y_pred_mean, DUMMY_VAR__);
        current_statement_begin__ = 346;
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        validate_non_negative_index("y_pred_var_chol", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> y_pred_var_chol(n_pred, n_pred);
        stan::math::initialize(y_pred_var_chol, DUMMY_VAR__);
        stan::math::fill(y_pred_var_chol, DUMMY_VAR__);
        current_statement_begin__ = 348;
        int n_all(0);
        (void) n_all;  // dummy to suppress unused var warning
        stan::math::fill(n_all, std::numeric_limits<int>::min());
        stan::math::assign(n_all,(n_pred + n));
        current_statement_begin__ = 349;
        validate_non_negative_index("x_all", "n_all", n_all);
        validate_non_negative_index("x_all", "d", d);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> x_all(n_all, d);
        stan::math::initialize(x_all, DUMMY_VAR__);
        stan::math::fill(x_all, DUMMY_VAR__);
        stan::math::assign(x_all,append_row(x_pred, x));
        current_statement_begin__ = 350;
        validate_non_negative_index("G_all", "n_all", n_all);
        validate_non_negative_index("G_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> G_all(n_all, n_all);
        stan::math::initialize(G_all, DUMMY_VAR__);
        stan::math::fill(G_all, DUMMY_VAR__);
        stan::math::assign(G_all,get_cor_mat(x_all, rhoG, pstream__));
        current_statement_begin__ = 351;
        validate_non_negative_index("L_all", "n_all", n_all);
        validate_non_negative_index("L_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> L_all(n_all, n_all);
        stan::math::initialize(L_all, DUMMY_VAR__);
        stan::math::fill(L_all, DUMMY_VAR__);
        stan::math::assign(L_all,get_cor_mat(x_all, rhoL, pstream__));
        current_statement_begin__ = 352;
        validate_non_negative_index("R_all", "n_all", n_all);
        validate_non_negative_index("R_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R_all(n_all, n_all);
        stan::math::initialize(R_all, DUMMY_VAR__);
        stan::math::fill(R_all, DUMMY_VAR__);
        stan::math::assign(R_all,combine_cor_mats(w, G_all, L_all, pstream__));
        current_statement_begin__ = 353;
        validate_non_negative_index("C_all", "n_all", n_all);
        validate_non_negative_index("C_all", "n_all", n_all);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_all(n_all, n_all);
        stan::math::initialize(C_all, DUMMY_VAR__);
        stan::math::fill(C_all, DUMMY_VAR__);
        stan::math::assign(C_all,get_cov_mat_s(sigma2, R_all, sigma2eps, pstream__));
        current_statement_begin__ = 354;
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        validate_non_negative_index("C_pred", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_pred(n_pred, n_pred);
        stan::math::initialize(C_pred, DUMMY_VAR__);
        stan::math::fill(C_pred, DUMMY_VAR__);
        stan::math::assign(C_pred,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 355;
        validate_non_negative_index("C_L", "n", n);
        validate_non_negative_index("C_L", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L(n, n);
        stan::math::initialize(C_L, DUMMY_VAR__);
        stan::math::fill(C_L, DUMMY_VAR__);
        stan::math::assign(C_L,cholesky_decompose(stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::nil_index_list())), "C_all")));
        current_statement_begin__ = 356;
        validate_non_negative_index("C_cross", "n", n);
        validate_non_negative_index("C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_cross(n, n_pred);
        stan::math::initialize(C_cross, DUMMY_VAR__);
        stan::math::fill(C_cross, DUMMY_VAR__);
        stan::math::assign(C_cross,stan::model::rvalue(C_all, stan::model::cons_list(stan::model::index_min((n_pred + 1)), stan::model::cons_list(stan::model::index_min_max(1, n_pred), stan::model::nil_index_list())), "C_all"));
        current_statement_begin__ = 358;
        validate_non_negative_index("y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_minus_beta0(n);
        stan::math::initialize(y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(y_minus_beta0,subtract(y, beta0));
        current_statement_begin__ = 359;
        validate_non_negative_index("C_L_inv_y_minus_beta0", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> C_L_inv_y_minus_beta0(n);
        stan::math::initialize(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::fill(C_L_inv_y_minus_beta0, DUMMY_VAR__);
        stan::math::assign(C_L_inv_y_minus_beta0,mdivide_left_tri_low(C_L, y_minus_beta0));
        current_statement_begin__ = 360;
        validate_non_negative_index("C_L_inv_C_cross", "n", n);
        validate_non_negative_index("C_L_inv_C_cross", "n_pred", n_pred);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L_inv_C_cross(n, n_pred);
        stan::math::initialize(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::fill(C_L_inv_C_cross, DUMMY_VAR__);
        stan::math::assign(C_L_inv_C_cross,mdivide_left_tri_low(C_L, C_cross));
        current_statement_begin__ = 362;
        stan::math::assign(y_pred_mean, add(beta0, multiply(transpose(C_L_inv_C_cross), C_L_inv_y_minus_beta0)));
        current_statement_begin__ = 363;
        stan::math::assign(y_pred_var_chol, cholesky_decompose(subtract(C_pred, multiply(transpose(C_L_inv_C_cross), C_L_inv_C_cross))));
        current_statement_begin__ = 366;
        stan::math::assign(y_pred, multi_normal_cholesky_rng(y_pred_mean, y_pred_var_chol, base_rng__));
        }
        current_statement_begin__ = 368;
        return stan::math::promote_scalar<fun_return_scalar_t__>(y_pred);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gp_pred_comp_s_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, class RNG>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__>::type>::type>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& x,
                       const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                       const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& x_pred,
                       const T3__& beta0,
                       const T4__& w,
                       const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& rhoL,
                       const Eigen::Matrix<T6__, Eigen::Dynamic, 1>& rhoG,
                       const T7__& sigma2eps,
                       const T8__& sigma2, RNG& base_rng__, std::ostream* pstream__) const {
        return gp_pred_comp_s_rng(x, y, x_pred, beta0, w, rhoL, rhoG, sigma2eps, sigma2, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_stanNonCompS_with_pred : public prob_grad {
private:
        int n;
        int d;
        vector_d y;
        matrix_d x;
        vector_d rho_alpha;
        vector_d rho_beta;
        double sigma2_alpha;
        double sigma2_beta;
        double sigma2eps_alpha;
        double sigma2eps_beta;
        int n_pred;
        matrix_d x_pred;
public:
    model_stanNonCompS_with_pred(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_stanNonCompS_with_pred(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_stanNonCompS_with_pred_namespace::model_stanNonCompS_with_pred";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 374;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 1);
            current_statement_begin__ = 375;
            context__.validate_dims("data initialization", "d", "int", context__.to_vec());
            d = int(0);
            vals_i__ = context__.vals_i("d");
            pos__ = 0;
            d = vals_i__[pos__++];
            check_greater_or_equal(function__, "d", d, 1);
            current_statement_begin__ = 376;
            validate_non_negative_index("y", "n", n);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(n));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 377;
            validate_non_negative_index("x", "n", n);
            validate_non_negative_index("x", "d", d);
            context__.validate_dims("data initialization", "x", "matrix_d", context__.to_vec(n,d));
            x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, d);
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_j_2_max__ = d;
            size_t x_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    x(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 379;
            validate_non_negative_index("rho_alpha", "d", d);
            context__.validate_dims("data initialization", "rho_alpha", "vector_d", context__.to_vec(d));
            rho_alpha = Eigen::Matrix<double, Eigen::Dynamic, 1>(d);
            vals_r__ = context__.vals_r("rho_alpha");
            pos__ = 0;
            size_t rho_alpha_j_1_max__ = d;
            for (size_t j_1__ = 0; j_1__ < rho_alpha_j_1_max__; ++j_1__) {
                rho_alpha(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "rho_alpha", rho_alpha, 0);
            current_statement_begin__ = 380;
            validate_non_negative_index("rho_beta", "d", d);
            context__.validate_dims("data initialization", "rho_beta", "vector_d", context__.to_vec(d));
            rho_beta = Eigen::Matrix<double, Eigen::Dynamic, 1>(d);
            vals_r__ = context__.vals_r("rho_beta");
            pos__ = 0;
            size_t rho_beta_j_1_max__ = d;
            for (size_t j_1__ = 0; j_1__ < rho_beta_j_1_max__; ++j_1__) {
                rho_beta(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "rho_beta", rho_beta, 0);
            current_statement_begin__ = 381;
            context__.validate_dims("data initialization", "sigma2_alpha", "double", context__.to_vec());
            sigma2_alpha = double(0);
            vals_r__ = context__.vals_r("sigma2_alpha");
            pos__ = 0;
            sigma2_alpha = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma2_alpha", sigma2_alpha, 0);
            current_statement_begin__ = 382;
            context__.validate_dims("data initialization", "sigma2_beta", "double", context__.to_vec());
            sigma2_beta = double(0);
            vals_r__ = context__.vals_r("sigma2_beta");
            pos__ = 0;
            sigma2_beta = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma2_beta", sigma2_beta, 0);
            current_statement_begin__ = 383;
            context__.validate_dims("data initialization", "sigma2eps_alpha", "double", context__.to_vec());
            sigma2eps_alpha = double(0);
            vals_r__ = context__.vals_r("sigma2eps_alpha");
            pos__ = 0;
            sigma2eps_alpha = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma2eps_alpha", sigma2eps_alpha, 0);
            current_statement_begin__ = 384;
            context__.validate_dims("data initialization", "sigma2eps_beta", "double", context__.to_vec());
            sigma2eps_beta = double(0);
            vals_r__ = context__.vals_r("sigma2eps_beta");
            pos__ = 0;
            sigma2eps_beta = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma2eps_beta", sigma2eps_beta, 0);
            current_statement_begin__ = 386;
            context__.validate_dims("data initialization", "n_pred", "int", context__.to_vec());
            n_pred = int(0);
            vals_i__ = context__.vals_i("n_pred");
            pos__ = 0;
            n_pred = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_pred", n_pred, 1);
            current_statement_begin__ = 387;
            validate_non_negative_index("x_pred", "n_pred", n_pred);
            validate_non_negative_index("x_pred", "d", d);
            context__.validate_dims("data initialization", "x_pred", "matrix_d", context__.to_vec(n_pred,d));
            x_pred = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n_pred, d);
            vals_r__ = context__.vals_r("x_pred");
            pos__ = 0;
            size_t x_pred_j_2_max__ = d;
            size_t x_pred_j_1_max__ = n_pred;
            for (size_t j_2__ = 0; j_2__ < x_pred_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_pred_j_1_max__; ++j_1__) {
                    x_pred(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 392;
            num_params_r__ += 1;
            current_statement_begin__ = 393;
            validate_non_negative_index("rho", "d", d);
            num_params_r__ += d;
            current_statement_begin__ = 394;
            num_params_r__ += 1;
            current_statement_begin__ = 395;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_stanNonCompS_with_pred() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 392;
        if (!(context__.contains_r("beta0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "beta0", "double", context__.to_vec());
        double beta0(0);
        beta0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(beta0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 393;
        if (!(context__.contains_r("rho")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable rho missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("rho");
        pos__ = 0U;
        validate_non_negative_index("rho", "d", d);
        context__.validate_dims("parameter initialization", "rho", "vector_d", context__.to_vec(d));
        Eigen::Matrix<double, Eigen::Dynamic, 1> rho(d);
        size_t rho_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
            rho(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lub_unconstrain(0, 1, rho);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable rho: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 394;
        if (!(context__.contains_r("sigma2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma2", "double", context__.to_vec());
        double sigma2(0);
        sigma2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 395;
        if (!(context__.contains_r("sigma2eps")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma2eps missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma2eps");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma2eps", "double", context__.to_vec());
        double sigma2eps(0);
        sigma2eps = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma2eps);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma2eps: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 392;
            local_scalar_t__ beta0;
            (void) beta0;  // dummy to suppress unused var warning
            if (jacobian__)
                beta0 = in__.scalar_constrain(lp__);
            else
                beta0 = in__.scalar_constrain();
            current_statement_begin__ = 393;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> rho;
            (void) rho;  // dummy to suppress unused var warning
            if (jacobian__)
                rho = in__.vector_lub_constrain(0, 1, d, lp__);
            else
                rho = in__.vector_lub_constrain(0, 1, d);
            current_statement_begin__ = 394;
            local_scalar_t__ sigma2;
            (void) sigma2;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma2 = in__.scalar_lb_constrain(0, lp__);
            else
                sigma2 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 395;
            local_scalar_t__ sigma2eps;
            (void) sigma2eps;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma2eps = in__.scalar_lb_constrain(0, lp__);
            else
                sigma2eps = in__.scalar_lb_constrain(0);
            // model body
            {
            current_statement_begin__ = 400;
            validate_non_negative_index("C_L", "n", n);
            validate_non_negative_index("C_L", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C_L(n, n);
            stan::math::initialize(C_L, DUMMY_VAR__);
            stan::math::fill(C_L, DUMMY_VAR__);
            current_statement_begin__ = 401;
            validate_non_negative_index("beta0_vec", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta0_vec(n);
            stan::math::initialize(beta0_vec, DUMMY_VAR__);
            stan::math::fill(beta0_vec, DUMMY_VAR__);
            {
            current_statement_begin__ = 404;
            validate_non_negative_index("R", "n", n);
            validate_non_negative_index("R", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> R(n, n);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            stan::math::assign(R,get_cor_mat(x, rho, pstream__));
            current_statement_begin__ = 405;
            validate_non_negative_index("C", "n", n);
            validate_non_negative_index("C", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> C(n, n);
            stan::math::initialize(C, DUMMY_VAR__);
            stan::math::fill(C, DUMMY_VAR__);
            stan::math::assign(C,get_cov_mat_s(sigma2, R, sigma2eps, pstream__));
            current_statement_begin__ = 406;
            stan::math::assign(C_L, cholesky_decompose(C));
            current_statement_begin__ = 407;
            stan::math::assign(beta0_vec, rep_vector(beta0, n));
            }
            current_statement_begin__ = 412;
            for (int i = 1; i <= d; ++i) {
                current_statement_begin__ = 413;
                lp_accum__.add(beta_log<propto__>(get_base1(rho, i, "rho", 1), get_base1(rho_alpha, i, "rho_alpha", 1), get_base1(rho_beta, i, "rho_beta", 1)));
            }
            current_statement_begin__ = 414;
            lp_accum__.add(gamma_log<propto__>(sigma2, sigma2_alpha, (1 / sigma2_beta)));
            current_statement_begin__ = 415;
            lp_accum__.add(gamma_log<propto__>(sigma2eps, sigma2eps_alpha, (1 / sigma2eps_beta)));
            current_statement_begin__ = 417;
            lp_accum__.add(multi_normal_cholesky_log<propto__>(y, beta0_vec, C_L));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("beta0");
        names__.push_back("rho");
        names__.push_back("sigma2");
        names__.push_back("sigma2eps");
        names__.push_back("y_pred");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_pred);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_stanNonCompS_with_pred_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double beta0 = in__.scalar_constrain();
        vars__.push_back(beta0);
        Eigen::Matrix<double, Eigen::Dynamic, 1> rho = in__.vector_lub_constrain(0, 1, d);
        size_t rho_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
            vars__.push_back(rho(j_1__));
        }
        double sigma2 = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma2);
        double sigma2eps = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma2eps);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 422;
            validate_non_negative_index("y_pred", "n_pred", n_pred);
            Eigen::Matrix<double, Eigen::Dynamic, 1> y_pred(n_pred);
            stan::math::initialize(y_pred, DUMMY_VAR__);
            stan::math::fill(y_pred, DUMMY_VAR__);
            stan::math::assign(y_pred,gp_pred_noncomp_s_rng(x, y, x_pred, beta0, rho, sigma2eps, sigma2, base_rng__, pstream__));
            // validate, write generated quantities
            current_statement_begin__ = 422;
            size_t y_pred_j_1_max__ = n_pred;
            for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
                vars__.push_back(y_pred(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_stanNonCompS_with_pred";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "beta0";
        param_names__.push_back(param_name_stream__.str());
        size_t rho_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "rho" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2eps";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "beta0";
        param_names__.push_back(param_name_stream__.str());
        size_t rho_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "rho" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2eps";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_stanNonCompS_with_pred_namespace::model_stanNonCompS_with_pred stan_model;
#endif
